# Site
name: '@softwareshinobi'

description: ''

logo: 'assets/images/logo.png'

favicon: 'assets/images/favicon.ico'

baseurl: '/'

disqus: 'demowebsite'

email: 'the.software.shinobi@gmail.com'

mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]

permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
        name:           "@softwareshinobi"

        neeame: "Software Shinobi"

        display_name: "Software Shinobi"

        email: the.software.shinobi@gmail.com

        site: https://links.softwareshinobi.digital

        twitter: https://links.softwareshinobi.digital

        description: "Freelance Software Developer & Technical Writer. I design, code, test, document, and deploy software things."

        avatar: 'assets/images/valorant/softwareshinobi.jpg'

        bio: "Freelance Software Developer & Technical Writer. I design, code, test, document, and deploy software things."

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
